#ifndef HAL_CONFIG_DEVICE_H
#define HAL_CONFIG_DEVICE_H

#include "em_device.h"
#include "hal-config-types.h"

// This file is auto-generated by Hardware Configurator in Simplicity Studio.
// Any content between $[ and ]$ will be replaced whenever the file is regenerated.
// Content outside these regions will be preserved.

// $[ACMP0]
// [ACMP0]$

// $[ACMP1]
// [ACMP1]$

// $[ADC0]
// [ADC0]$

// $[ANTDIV]
// [ANTDIV]$

// $[BATTERYMON]
// [BATTERYMON]$

// $[BTL_BUTTON]
// [BTL_BUTTON]$

// $[BULBPWM]
// [BULBPWM]$

// $[BULBPWM_COLOR]
// [BULBPWM_COLOR]$

// $[BUTTON]
// [BUTTON]$

// $[CMU]
#define HAL_CLK_HFCLK_SOURCE                 (HAL_CLK_HFCLK_SOURCE_HFRCO)
#define HAL_CLK_LFECLK_SOURCE                (HAL_CLK_LFCLK_SOURCE_DISABLED)
#define HAL_CLK_LFBCLK_SOURCE                (HAL_CLK_LFCLK_SOURCE_DISABLED)
#define BSP_CLK_LFXO_PRESENT                 (1)
#define BSP_CLK_HFXO_PRESENT                 (1)
#define BSP_CLK_LFXO_INIT                     CMU_LFXOINIT_DEFAULT
#define BSP_CLK_LFXO_CTUNE                   (0U)
#define BSP_CLK_LFXO_FREQ                    (32768U)
#define HAL_CLK_LFACLK_SOURCE                (HAL_CLK_LFCLK_SOURCE_DISABLED)
#define BSP_CLK_HFXO_FREQ                    (38400000UL)
#define BSP_CLK_HFXO_CTUNE                   (-1)
#define BSP_CLK_HFXO_INIT                     CMU_HFXOINIT_DEFAULT
#define HAL_CLK_HFXO_AUTOSTART               (HAL_CLK_HFXO_AUTOSTART_NONE)
// [CMU]$

// $[COEX]
// [COEX]$

// $[CS5463]
// [CS5463]$

// $[CSEN]
// [CSEN]$

// $[DCDC]
#define BSP_DCDC_PRESENT                     (1)

#define HAL_DCDC_BYPASS                      (0)
#define BSP_DCDC_INIT                         EMU_DCDCINIT_DEFAULT
// [DCDC]$

// $[EMU]
// [EMU]$

// $[EXTFLASH]
// [EXTFLASH]$

// $[EZRADIOPRO]
// [EZRADIOPRO]$

// $[FEM]
// [FEM]$

// $[GPIO]
// [GPIO]$

// $[I2C0]
// [I2C0]$

// $[I2C1]
// [I2C1]$

// $[I2CSENSOR]
// [I2CSENSOR]$

// $[IDAC0]
// [IDAC0]$

// $[IOEXP]
// [IOEXP]$

// $[LED]
#define BSP_LED_PRESENT                      (1)

#define BSP_LED0_PIN                         (13U)
#define BSP_LED0_PORT                        (gpioPortD)

#define BSP_LED1_PIN                         (14U)
#define BSP_LED1_PORT                        (gpioPortD)

#define BSP_LED2_PIN                         (15U)
#define BSP_LED2_PORT                        (gpioPortD)

#define BSP_LED3_PIN                         (13U)
#define BSP_LED3_PORT                        (gpioPortB)

#define BSP_LED_POLARITY                     (1)
#define BSP_LED_COUNT                        (4U)
#define BSP_LED_INIT                         { { BSP_LED0_PORT, BSP_LED0_PIN }, { BSP_LED1_PORT, BSP_LED1_PIN }, { BSP_LED2_PORT, BSP_LED2_PIN }, { BSP_LED3_PORT, BSP_LED3_PIN } }
// [LED]$

// $[LESENSE]
// [LESENSE]$

// $[LETIMER0]
// [LETIMER0]$

// $[LEUART0]
// [LEUART0]$

// $[LFXO]
// [LFXO]$

// $[MODEM]
// [MODEM]$

// $[PA]
#define HAL_PA_ENABLE                        (1)

#define HAL_PA_RAMP                          (10UL)
#define HAL_PA_2P4_LOWPOWER                  (0)
#define HAL_PA_POWER                         (252U)
#define BSP_PA_VOLTAGE                       (3300U)
#define HAL_PA_CURVE_HEADER                   "pa_curves_efr32.h"
// [PA]$

// $[PCNT0]
// [PCNT0]$

// $[PORTIO]
// [PORTIO]$

// $[PRS]
// [PRS]$

// $[PTI]
// [PTI]$

// $[PYD1698]
// [PYD1698]$

// $[SERIAL]
#define BSP_SERIAL_APP_PORT                  (HAL_SERIAL_PORT_USART0)
#define BSP_SERIAL_APP_CTS_PIN               (11U)
#define BSP_SERIAL_APP_CTS_PORT              (gpioPortB)
#define BSP_SERIAL_APP_CTS_LOC               (2U)

#define BSP_SERIAL_APP_RX_PIN                (1U)
#define BSP_SERIAL_APP_RX_PORT               (gpioPortA)
#define BSP_SERIAL_APP_RX_LOC                (0U)

#define BSP_SERIAL_APP_TX_PIN                (0U)
#define BSP_SERIAL_APP_TX_PORT               (gpioPortA)
#define BSP_SERIAL_APP_TX_LOC                (0U)

#define HAL_SERIAL_APP_BAUD_RATE             (115200UL)
#define HAL_SERIAL_APP_FLOW_CONTROL          (HAL_USART_FLOW_CONTROL_NONE)
// [SERIAL]$

// $[SPIDISPLAY]
// [SPIDISPLAY]$

// $[SPINCP]
// [SPINCP]$

// $[TIMER0]
// [TIMER0]$

// $[TIMER1]
// [TIMER1]$

// $[UARTNCP]
// [UARTNCP]$

// $[USART0]
#define PORTIO_USART0_CTS_PIN                (11U)
#define PORTIO_USART0_CTS_PORT               (gpioPortB)
#define PORTIO_USART0_CTS_LOC                (2U)

#define PORTIO_USART0_RX_PIN                 (1U)
#define PORTIO_USART0_RX_PORT                (gpioPortA)
#define PORTIO_USART0_RX_LOC                 (0U)

#define PORTIO_USART0_TX_PIN                 (0U)
#define PORTIO_USART0_TX_PORT                (gpioPortA)
#define PORTIO_USART0_TX_LOC                 (0U)

#define HAL_USART0_ENABLE                    (1)

#define BSP_USART0_CTS_PIN                   (11U)
#define BSP_USART0_CTS_PORT                  (gpioPortB)
#define BSP_USART0_CTS_LOC                   (2U)
#define ESP32_CTS_PIN                        (11U)
#define ESP32_CTS_PORT                       (gpioPortB)
#define ESP32_CTS_LOC                        (2U)

#define BSP_USART0_RX_PIN                    (1U)
#define BSP_USART0_RX_PORT                   (gpioPortA)
#define BSP_USART0_RX_LOC                    (0U)
#define ESP32_RX_PIN                         (1U)
#define ESP32_RX_PORT                        (gpioPortA)
#define ESP32_RX_LOC                         (0U)

#define BSP_USART0_TX_PIN                    (0U)
#define BSP_USART0_TX_PORT                   (gpioPortA)
#define BSP_USART0_TX_LOC                    (0U)
#define ESP32_TX_PIN                         (0U)
#define ESP32_TX_PORT                        (gpioPortA)
#define ESP32_TX_LOC                         (0U)

#define HAL_USART0_BAUD_RATE                 (115200UL)
#define HAL_USART0_FLOW_CONTROL              (HAL_USART_FLOW_CONTROL_NONE)
#define ESP32_BAUD_RATE                      (115200UL)
#define ESP32_FLOW_CONTROL                   (HAL_USART_FLOW_CONTROL_NONE)
// [USART0]$

// $[USART1]
// [USART1]$

// $[USART2]
// [USART2]$

// $[VCOM]
// [VCOM]$

// $[VDAC0]
// [VDAC0]$

// $[VUART]
// [VUART]$

// $[WDOG]
// [WDOG]$

// $[WTIMER0]
// [WTIMER0]$

#if defined(_SILICON_LABS_MODULE)
#include "sl_module.h"
#endif

#endif /* HAL_CONFIG_DEVICE_H */

